import { useTRPC } from "@/trpc/client";
import { useWorkflowsParams } from "./use-workflows-params";
import {
  useSuspenseQuery,
  useQueryClient,
  useMutation,
} from "@tanstack/react-query";
import { toast } from "sonner";

// Hook to fetch all workflows using Suspense

export const useSuspenseWorkflows = () => {
  const trpc = useTRPC();
  //useTRPC() is a custom hook that provides access to the TRPC client instance. It allows you to make queries and mutations to the server using the TRPC API.
  // prefetch - load data in server side cache
  // hydrate - load data from server side cache to client side cache(React Query cache)
  //usetrpc() - load data from react query cache if available, otherwise fetch from server and store in cache
  const [params] = useWorkflowsParams();

  return useSuspenseQuery(trpc.workflows.getMany.queryOptions(params));
  //useSuspenseQuery is a hook from React Query that allows you to fetch data and suspend rendering until the data is available. It takes a query key and a query function as arguments. In this case, it uses the query options generated by trpc.workflows.getMany.queryOptions(params) to fetch the workflows based on the provided parameters.
};

//Hook to create a new workflow

export const useCreateWorkflow = () => {
  const queryClient = useQueryClient();
  //useQueryClient() is a hook from React Query that provides access to the query client instance. It allows you to interact with the cache and perform actions like invalidating queries or updating cached data.

  const trpc = useTRPC();

  return trpc.workflows.create.mutationOptions({
    onSuccess: (data) => {
      toast.success(`Workflow created: ${data.name}`);
      queryClient.invalidateQueries(trpc.workflows.getMany.queryOptions({}));
      //invalidateQueries is a method from React Query that allows you to mark specific queries as stale, triggering a refetch the next time they are accessed. In this case, it invalidates the query for fetching all workflows, ensuring that the newly created workflow is included in the updated list when the query is refetched.
    },
    onError: (error) => {
      toast.error(`Error creating workflow: ${error.message}`);
    },
  });
};

// Hook to remove a workflow

export const useRemoveWorkflow = () => {
  const trpc = useTRPC();
  const queryClient = useQueryClient();

  return useMutation(
    trpc.workflows.remove.mutationOptions({
      onSuccess: (data) => {
        toast.success(`Workflow "${data.name}" removed`);
        queryClient.invalidateQueries(trpc.workflows.getMany.queryOptions({}));
        //queryOptions is a method from the TRPC client that generates the query options for fetching workflows based on the provided parameters. In this case, it generates the query options for fetching all workflows, ensuring that the removed workflow is no longer included in the updated list when the query is refetched.
        queryClient.invalidateQueries(
          trpc.workflows.getOne.queryFilter({ id: data.id }),
          //queryFilter is a method from the TRPC client that generates the query filter for fetching a specific workflow based on the provided parameters. In this case, it generates the query filter for fetching the removed workflow by its ID, ensuring that any cached data related to that specific workflow is invalidated and removed from the cache.
        );
      },
    }),
  );
};

/**
 * Hook to fetch a single workflow using suspense
 */
export const useSuspenseWorkflow = (id: string) => {
  const trpc = useTRPC();
  return useSuspenseQuery(trpc.workflows.getOne.queryOptions({ id }));
};

/**
 * Hook to update a workflow name
 */
export const useUpdateWorkflowName = () => {
  const queryClient = useQueryClient();
  const trpc = useTRPC();

  return useMutation(
    trpc.workflows.updateName.mutationOptions({
      onSuccess: (data) => {
        toast.success(`Workflow "${data.name}" updated`);
        queryClient.invalidateQueries(trpc.workflows.getMany.queryOptions({}));
        queryClient.invalidateQueries(
          trpc.workflows.getOne.queryOptions({ id: data.id }),
        );
      },
      onError: (error) => {
        toast.error(`Failed to update workflow: ${error.message}`);
      },
    }),
  );
};

/**
 * Hook to update a workflow
 */
export const useUpdateWorkflow = () => {
  const queryClient = useQueryClient();
  const trpc = useTRPC();

  return useMutation(
    trpc.workflows.update.mutationOptions({
      onSuccess: (data) => {
        toast.success(`Workflow "${data.name}" saved`);
        queryClient.invalidateQueries(trpc.workflows.getMany.queryOptions({}));
        queryClient.invalidateQueries(
          trpc.workflows.getOne.queryOptions({ id: data.id }),
        );
      },
      onError: (error) => {
        toast.error(`Failed to save workflow: ${error.message}`);
      },
    }),
  );
};

/**
 * Hook to execute a workflow
 */
export const useExecuteWorkflow = () => {
  const trpc = useTRPC();

  return useMutation(
    trpc.workflows.execute.mutationOptions({
      onSuccess: (data) => {
        toast.success(`Workflow "${data.name}" executed`);
      },
      onError: (error) => {
        toast.error(`Failed to execute workflow: ${error.message}`);
      },
    }),
  );
};
